#requires -Version 7.3

<#
.SYNOPSIS
    Renders the Homebrew formula for relaypublisher from a stable release's SHA256SUMS.txt.

.DESCRIPTION
    The formula installs the self-contained osx-arm64 single-file app attached to the GitHub release
    of the given version. Its sha256 is taken from that release's SHA256SUMS.txt, so the formula pins
    exactly the archive release-draft.yml produced. Prerelease versions are rejected because the
    Homebrew tap only carries stable releases.

    release-publish.yml runs this script and opens a pull request against the tap with the result.
    See doc/03-ci-github-actions.md section 12a and doc/00-overview.md section 6.17.

.EXAMPLE
    ./tools/New-HomebrewFormula.ps1 -Version 1.1.1 -Sha256SumsPath ./SHA256SUMS.txt -Repository kkamegawa/Relaypublisher -OutputPath ./Formula/relaypublisher.rb
#>

[CmdletBinding()]
param(
    # Stable release version without the leading "v", for example 1.1.1.
    [string]$Version,

    # SHA256SUMS.txt attached to the release (sha256sum output).
    [string]$Sha256SumsPath,

    # GitHub repository hosting the release, as owner/name.
    [string]$Repository,

    # Where to write the formula. Missing parent directories are created.
    [string]$OutputPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#region Formula helpers

# Same shape as the release tag check in release-draft.yml, minus the prerelease suffix.
$StableVersionPattern = '^[0-9]+\.[0-9]+\.[0-9]+$'
# GitHub owners are alphanumeric with hyphens; repository names also allow '.' and '_'. Anything else
# (quotes, '#', whitespace) is refused so it can never break out of the Ruby string literals below.
$RepositoryPattern = '^[A-Za-z0-9][A-Za-z0-9-]{0,38}/[A-Za-z0-9._-]{1,100}$'
# One sha256sum line: the hash, a space, then a space (text mode) or '*' (binary mode) and the name.
$ChecksumLinePattern = '^(?<hash>[0-9A-Fa-f]{64}) [ *](?<name>.+)$'

function Test-StableVersion {
    param([string]$Value)
    return (-not [string]::IsNullOrEmpty($Value)) -and ($Value -cmatch $StableVersionPattern)
}

function Test-RepositoryName {
    param([string]$Value)
    return (-not [string]::IsNullOrEmpty($Value)) -and ($Value -cmatch $RepositoryPattern)
}

function Get-HomebrewArchiveName {
    param([Parameter(Mandatory = $true)][string]$Version)
    return "relaypublisher-$Version-osx-arm64.zip"
}

function Get-ArchiveSha256 {
    param(
        [Parameter(Mandatory = $true)][AllowEmptyCollection()][AllowEmptyString()][string[]]$Lines,
        [Parameter(Mandatory = $true)][string]$ArchiveName
    )

    $found = [System.Collections.Generic.List[string]]::new()
    $lineNumber = 0
    foreach ($rawLine in $Lines) {
        $lineNumber++
        $line = $rawLine.TrimEnd("`r")
        if ([string]::IsNullOrWhiteSpace($line)) {
            continue
        }

        $match = [regex]::Match($line, $ChecksumLinePattern)
        if (-not $match.Success) {
            throw "SHA256SUMS line $lineNumber is not '<sha256>  <file>': $line"
        }

        # release-draft.yml hashes './*.zip', so names usually carry a './' prefix.
        $name = $match.Groups['name'].Value
        if ($name.StartsWith('./', [System.StringComparison]::Ordinal)) {
            $name = $name.Substring(2)
        }

        if ($name -ceq $ArchiveName) {
            $found.Add($match.Groups['hash'].Value.ToLowerInvariant())
        }
    }

    if ($found.Count -eq 0) {
        throw "SHA256SUMS has no entry for $ArchiveName."
    }
    if ($found.Count -gt 1) {
        throw "SHA256SUMS has $($found.Count) entries for $ArchiveName; expected exactly one."
    }
    return $found[0]
}

function New-HomebrewFormulaText {
    param(
        [Parameter(Mandatory = $true)][string]$Version,
        [Parameter(Mandatory = $true)][string]$Sha256,
        [Parameter(Mandatory = $true)][string]$Repository
    )

    if (-not (Test-StableVersion $Version)) {
        throw "Version '$Version' is not a stable MAJOR.MINOR.PATCH version; the Homebrew tap only carries stable releases."
    }
    if (-not (Test-RepositoryName $Repository)) {
        throw "Repository '$Repository' is not an owner/name GitHub repository."
    }
    if ($Sha256 -cnotmatch '^[0-9a-f]{64}$') {
        throw 'Sha256 must be 64 lower-case hexadecimal characters.'
    }

    $archive = Get-HomebrewArchiveName -Version $Version
    $lines = @(
        "# Generated by tools/New-HomebrewFormula.ps1 in $Repository for release v$Version."
        '# Do not edit by hand: the release workflow regenerates this file for every stable release.'
        'class Relaypublisher < Formula'
        '  desc "Publish winget-like YAML manifests as Microsoft Intune LOB apps"'
        "  homepage `"https://github.com/$Repository`""
        "  url `"https://github.com/$Repository/releases/download/v$Version/$archive`""
        "  sha256 `"$Sha256`""
        '  license "MIT"'
        ''
        '  # The release ships a self-contained single-file app for Apple silicon only.'
        '  depends_on arch: :arm64'
        '  depends_on :macos'
        ''
        '  def install'
        '    bin.install "relaypublisher"'
        '  end'
        ''
        '  test do'
        '    assert_match version.to_s, shell_output("#{bin}/relaypublisher --version")'
        '  end'
        'end'
    )
    return ($lines -join "`n") + "`n"
}

function Resolve-UserPath {
    param([Parameter(Mandatory = $true)][string]$Path)
    # Resolve against the PowerShell location, not the process working directory.
    return $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($Path)
}

#endregion

#region Entry point

if (-not (Test-StableVersion $Version)) {
    throw "Version '$Version' is not a stable MAJOR.MINOR.PATCH version; the Homebrew tap only carries stable releases."
}
if (-not (Test-RepositoryName $Repository)) {
    throw "Repository '$Repository' is not an owner/name GitHub repository."
}
if ([string]::IsNullOrWhiteSpace($Sha256SumsPath)) {
    throw '-Sha256SumsPath is required.'
}
if ([string]::IsNullOrWhiteSpace($OutputPath)) {
    throw '-OutputPath is required.'
}

$sumsPath = Resolve-UserPath -Path $Sha256SumsPath
if (-not (Test-Path -LiteralPath $sumsPath -PathType Leaf)) {
    throw "SHA256SUMS file not found: $sumsPath"
}

$archiveSha256 = Get-ArchiveSha256 -Lines ([System.IO.File]::ReadAllLines($sumsPath)) -ArchiveName (Get-HomebrewArchiveName -Version $Version)
$formulaText = New-HomebrewFormulaText -Version $Version -Sha256 $archiveSha256 -Repository $Repository

$formulaPath = Resolve-UserPath -Path $OutputPath
[System.IO.Directory]::CreateDirectory([System.IO.Path]::GetDirectoryName($formulaPath)) | Out-Null
[System.IO.File]::WriteAllText($formulaPath, $formulaText, [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $formulaPath for relaypublisher $Version ($archiveSha256)."

#endregion
